Remove unused function to fix compilation
error: unused function 'random_read' [-Werror,-Wunused-function]
(cherry picked from commit a4ee3152c745c348e8ee27910f430f9cf1ccede4)